server:
  port: 8082

spring:
  application:
    name: ms-pedidos360-catalog
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pedidos360_catalog}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: ${DB_USER:pedidos360}
    password: ${DB_PASSWORD:pedidos360}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

azure:
  tenant-id: ${AZURE_TENANT_ID:391785ea-8a93-4b03-aa6f-34f76498a5ad}
  audience: ${AZURE_API_AUDIENCE:api://9f968a39-1844-4166-ada1-5833116eda90}
  roles-claim: ${AZURE_ROLES_CLAIM:roles}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: INFO
