server:
  port: 8080

spring:
  application:
    name: ms-pedidos360-bff

azure:
  tenant-id: ${AZURE_TENANT_ID:a49d895e-910c-431b-a321-f86038460e12}
  audience: ${AZURE_API_AUDIENCE:api://0a2fa07e-9f53-4caa-af3e-520c0dc8b941}
  roles-claim: ${AZURE_ROLES_CLAIM:roles}

downstream:
  orders:
    base-url: ${ORDERS_SERVICE_URL:http://52.55.28.57:8081}
  catalog:
    base-url: ${CATALOG_SERVICE_URL:http://54.160.14.153:8082}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: INFO
